document.addEventListener("DOMContentLoaded", () => {
  "use strict";
  const allProducts=window.TabanjiCatalog?.getProducts()||[];
  const allCategories=window.TabanjiCatalog?.getCategories()||[];
  const store=window.TabanjiStore||null,$=id=>document.getElementById(id),id=new URLSearchParams(location.search).get("id"),product=allProducts.find(item=>item.id===id);
  const els={content:$("productContent"),empty:$("emptyState"),breadcrumb:$("breadcrumb"),title:$("productTitle"),badge:$("badge"),brand:$("brandLink"),sku:$("sku"),seller:$("seller"),rating:$("rating"),reviewsLink:$("reviewsLink"),stock:$("stock"),desc:$("shortDescription"),old:$("oldPrice"),price:$("price"),discount:$("discount"),delivery:$("delivery"),low:$("lowStock"),qty:$("quantity"),minus:$("quantityMinus"),plus:$("quantityPlus"),cart:$("addToCart"),buy:$("buyNow"),favorite:$("favoriteButton"),compare:$("compareButton"),mainImage:$("mainImage"),thumbs:$("thumbnails"),prev:$("galleryPrev"),next:$("galleryNext"),lightbox:$("lightbox"),lightboxImage:$("lightboxImage"),toast:$("toast"),drawer:$("drawer"),menuOverlay:$("menuOverlay"),openMenu:$("openMenu"),closeMenu:$("closeMenu"),theme:$("themeToggle"),drawerTheme:$("drawerTheme"),search:$("searchInput"),searchForm:$("searchForm"),suggestions:$("suggestions"),formModal:$("formModal"),demoForm:$("demoForm")};
  let gallery=[],galleryIndex=0,suggestionItems=[],suggestionIndex=-1,toastTimer,lastFocus=null,activeModal=null;
  const money=(v,c="USD")=>new Intl.NumberFormat("en-US",{style:"currency",currency:c,maximumFractionDigits:0}).format(v);
  const el=(tag,className,text)=>{const n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=text;return n};
  const link=(text,href,className)=>{const n=el("a",className,text);n.href=href;return n};
  const fallback=()=> "data:image/svg+xml;charset=UTF-8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="640" height="480"><rect width="100%" height="100%" fill="#dfe5ee"/><text x="50%" y="48%" text-anchor="middle" font-size="72">📦</text><text x="50%" y="65%" text-anchor="middle" font-family="Arial" font-size="24" fill="#667085">Image unavailable</text></svg>');
  function showToast(message){els.toast.textContent=message;els.toast.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>els.toast.classList.remove("show"),2600)}
  function category(){return allCategories.find(c=>c.id===product?.categoryId)||null}
  function subName(){if(!product)return"";const cat=category();for(const group of cat?.groups||[]){const found=group.items.find(item=>slug(item)===product.subcategorySlug);if(found)return found}return product.subcategorySlug.split("-").map(w=>w[0]?.toUpperCase()+w.slice(1)).join(" ")}
  function slug(v){return String(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/&/g," and ").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"")}
  function svgVariant(label,index){const colors=["#1264d8","#334155","#0f766e","#7c3aed"],color=colors[(index+product.id.charCodeAt(product.id.length-1))%colors.length],safe=(product.brand+" "+product.title).replace(/[&<>"']/g,"").slice(0,34);return"data:image/svg+xml;charset=UTF-8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600"><rect width="100%" height="100%" fill="'+color+'"/><circle cx="680" cy="90" r="190" fill="white" opacity=".1"/><rect x="130" y="130" width="540" height="310" rx="28" fill="white" opacity=".1"/><text x="400" y="285" text-anchor="middle" font-family="Arial" font-size="42" font-weight="700" fill="white">'+safe+'</text><text x="400" y="345" text-anchor="middle" font-family="Arial" font-size="25" fill="white" opacity=".82">'+label+'</text><text x="400" y="500" text-anchor="middle" font-family="Arial" font-size="20" fill="white" opacity=".7">TABANJI</text></svg>')}
  function discount(){return product.oldPrice?Math.round((1-product.price/product.oldPrice)*100):0}
  function warranty(){if(["electronics","computers","gaming","appliances"].includes(product.categoryId))return"12 months";if(["tools","auto","energy"].includes(product.categoryId))return"6 months";return"14-day store guarantee"}

  function renderBreadcrumb(){const cat=category(),sub=subName();els.breadcrumb.append(link("Home","index.html"),el("span","","/"),link("Catalog","catalog.html"));if(cat)els.breadcrumb.append(el("span","","/"),link(cat.title,"products.html?category="+encodeURIComponent(product.categoryId)));els.breadcrumb.append(el("span","","/"),link(sub,"products.html?category="+encodeURIComponent(product.categoryId)+"&subcategory="+encodeURIComponent(product.subcategorySlug)),el("span","","/"),el("span","",product.title))}
  function renderMain(){
    document.title=product.title+" — TABANJI";document.querySelector('meta[name="description"]').content=product.shortDescription;renderBreadcrumb();
    els.title.textContent=product.title;els.badge.textContent=product.badge||"";els.brand.textContent=product.brand;els.brand.href="products.html?category="+encodeURIComponent(product.categoryId)+"&brand="+encodeURIComponent(product.brand);
    els.sku.textContent="SKU: "+product.sku;els.seller.textContent="Seller: "+product.seller;els.rating.textContent="★ "+product.rating;els.reviewsLink.textContent=product.reviewCount+" reviews";els.stock.textContent=product.inStock?"In stock · "+product.stockCount+" available":"Out of stock";els.stock.classList.toggle("out",!product.inStock);els.desc.textContent=product.shortDescription;els.old.textContent=product.oldPrice?money(product.oldPrice,product.currency):"";els.price.textContent=money(product.price,product.currency);els.discount.textContent=product.oldPrice?"−"+discount()+"%":"";els.delivery.textContent="🚚 "+product.deliveryText;els.low.textContent=product.inStock&&product.stockCount<=3?"Only "+product.stockCount+" left in stock.":"";els.qty.max=String(Math.max(1,product.stockCount));els.cart.disabled=!product.inStock;els.buy.disabled=!product.inStock;
    const services=[["🚚 Delivery",product.deliveryText],["💳 Payment","Card, cash on delivery, bank transfer"],["🛡 Warranty",warranty()],["↩ Returns","14 days, original condition"]];$("serviceGrid").replaceChildren(...services.map(([a,b])=>{const c=el("div","service-card");c.append(el("strong","",a),el("small","",b));return c}));
    refreshButtons();renderPanels();renderRecommendations();saveRecent();
  }
  function galleryAlt(i){return product.title+" — "+["main view","alternate view","detail view","packaging and lifestyle view"][i]}
  function renderGallery(){gallery=[product.image,svgVariant("Alternate view",1),svgVariant("Detail view",2),svgVariant("Packaging & lifestyle",3)];els.thumbs.replaceChildren(...gallery.map((src,i)=>{const b=el("button","thumb");b.type="button";b.dataset.index=String(i);b.setAttribute("role","option");b.setAttribute("aria-selected",String(i===0));b.setAttribute("aria-label","Show "+galleryAlt(i));const image=el("img");image.src=src;image.alt=galleryAlt(i);image.addEventListener("error",()=>image.src=fallback(),{once:true});b.append(image);return b}));showImage(0)}
  function showImage(index){galleryIndex=(index+gallery.length)%gallery.length;els.mainImage.src=gallery[galleryIndex];els.mainImage.alt=galleryAlt(galleryIndex);els.lightboxImage.src=gallery[galleryIndex];els.lightboxImage.alt=galleryAlt(galleryIndex);els.thumbs.querySelectorAll(".thumb").forEach((b,i)=>b.setAttribute("aria-selected",String(i===galleryIndex)))}
  function clampQty(){let value=Math.floor(Number(els.qty.value)||1);value=Math.max(1,Math.min(Math.max(1,product.stockCount),value));els.qty.value=String(value);return value}
  function refreshButtons(){if(!store){[els.cart,els.buy,els.favorite,els.compare].forEach(b=>b.disabled=true);return}const fav=store.isFavorite(product.id),cmp=store.isCompared(product.id);els.favorite.classList.toggle("active",fav);els.favorite.setAttribute("aria-pressed",String(fav));els.favorite.textContent=fav?"♥ Remove from favorites":"♡ Add to favorites";els.compare.classList.toggle("active",cmp);els.compare.setAttribute("aria-pressed",String(cmp));els.compare.textContent=cmp?"✓ Remove from compare":"⇄ Add to compare";store.updateHeaderCounters()}

  function renderPanels(){
    const desc=$("panel-description");desc.replaceChildren(el("h2","","About this product"),el("p","",product.shortDescription),el("p","","Designed for dependable everyday use, this TABANJI selection balances practical features, straightforward operation and solid value."));const highlights=el("ul","highlights");["Trusted marketplace seller","Convenient delivery options","Quality checked product"].forEach(t=>highlights.append(el("li","",t)));desc.append(highlights);
    const specs={...product.specifications,Brand:product.brand,Seller:product.seller,SKU:product.sku,Category:category()?.title||product.categoryId,Stock:product.inStock?product.stockCount+" units":"Out of stock"};const table=el("table","spec-table");Object.entries(specs).forEach(([k,v])=>{const row=el("tr");row.append(el("th","",k),el("td","",String(v)));table.append(row)});$("panel-specifications").replaceChildren(el("h2","","Specifications"),table);
    const delivery=$("panel-delivery");delivery.replaceChildren(el("h2","","Delivery & Payment"));[["Delivery",product.deliveryText],["Payment","Card, cash on delivery and bank transfer are available."],["Warranty",warranty()+" warranty or store guarantee."],["Returns","Returns are accepted within 14 days when the item remains in its original condition."]].forEach(([h,t])=>{const box=el("section","info-box");box.append(el("h3","",h),el("p","",t));delivery.append(box)});
    renderReviews();renderQuestions();
  }
  function seed(){return [...product.id].reduce((n,c)=>n+c.charCodeAt(0),0)}
  function renderReviews(){const panel=$("panel-reviews"),s=seed(),count=3+s%3,names=["Alex M.","Jordan K.","Sam R.","Taylor P.","Morgan D."],texts=["Exactly as described and easy to use.","Good value and careful packaging.","Delivery was quick and the quality feels solid.","A practical choice for everyday needs.","Everything worked correctly out of the box."],summary=el("div","review-summary"),big=el("div");big.append(el("div","big-rating",product.rating+"★"),el("small","",product.reviewCount+" verified ratings"));const dist=el("div","distribution");for(let star=5;star>=1;star--){const pct=Math.max(4,Math.min(88,(star===5?58:star===4?27:8)+(s+star)%8));const row=el("div","distribution-row");const bar=el("div","bar"),fill=el("span");fill.style.width=pct+"%";bar.append(fill);row.append(el("span","",star+"★"),bar,el("small","",pct+"%"));dist.append(row)}summary.append(big,dist);const button=el("button","panel-action","Write a review");button.type="button";button.dataset.openForm="review";panel.replaceChildren(el("h2","","Customer reviews"),summary,button);for(let i=0;i<count;i++){const review=el("article","review"),head=el("div","review-head");head.append(el("strong","",names[(s+i)%names.length]),el("span","verified","✓ Verified purchase"));review.append(head,el("div","rating-line","★".repeat(4+(s+i)%2)),el("small","",new Date(2026,5-(i%4),3+i*4).toLocaleDateString("en-US")),el("p","",texts[(s+i)%texts.length]),el("p","","Pros: Reliable quality and straightforward setup."),el("p","","Cons: Packaging could be more compact."));panel.append(review)}}
  function renderQuestions(){const panel=$("panel-questions"),questions=["Is this item covered by warranty?","How quickly can it be delivered?","Is everything needed for basic use included?"];panel.replaceChildren(el("h2","","Questions & answers"));questions.forEach((q,i)=>{const box=el("article","question"),btn=el("button","",q+" +"),answer=el("div","answer","TABANJI: "+[warranty()+" coverage applies to this product.",product.deliveryText+".","The standard package includes the components listed in the specifications."][i]);btn.type="button";btn.setAttribute("aria-expanded","false");answer.hidden=true;btn.addEventListener("click",()=>{const open=btn.getAttribute("aria-expanded")!=="true";btn.setAttribute("aria-expanded",String(open));answer.hidden=!open});box.append(btn,answer);panel.append(box)});const ask=el("button","panel-action","Ask a question");ask.type="button";ask.dataset.openForm="question";panel.append(ask)}

  function recommendationCard(item){const card=el("article","recommend-card");const main=link("","product.html?id="+encodeURIComponent(item.id));const image=el("img");image.src=item.image;image.alt=item.title;image.loading="lazy";image.addEventListener("error",()=>image.src=fallback(),{once:true});const body=el("div","recommend-body");body.append(el("strong","",item.title),el("span","rating-line","★ "+item.rating));if(item.oldPrice)body.append(el("span","recommend-old",money(item.oldPrice,item.currency)));body.append(el("span","recommend-price",money(item.price,item.currency)));main.append(image,body);const actions=el("div","recommend-actions"),fav=el("button","","♡"),cmp=el("button","","⇄");fav.type=cmp.type="button";fav.dataset.action="favorite";cmp.dataset.action="compare";fav.setAttribute("aria-label","Toggle favorite for "+item.title);cmp.setAttribute("aria-label","Toggle compare for "+item.title);actions.append(fav,cmp);const cart=el("button","recommend-cart","Add to cart");cart.type="button";cart.dataset.action="cart";cart.disabled=!item.inStock;card.dataset.productId=item.id;card.append(main,actions,cart);refreshRecommend(card,item);return card}
  function refreshRecommend(card,item){if(!store)return;const fav=card.querySelector('[data-action="favorite"]'),cmp=card.querySelector('[data-action="compare"]');fav.classList.toggle("active",store.isFavorite(item.id));fav.textContent=store.isFavorite(item.id)?"♥":"♡";cmp.classList.toggle("active",store.isCompared(item.id))}
  function renderRecommendations(){const same=allProducts.filter(p=>p.id!==product.id&&p.categoryId===product.categoryId).sort((a,b)=>(b.subcategorySlug===product.subcategorySlug)-(a.subcategorySlug===product.subcategorySlug)).slice(0,8);$("similarProducts").replaceChildren(...same.map(recommendationCard));const cats=allCategories.map(c=>c.id),index=Math.max(0,cats.indexOf(product.categoryId)),neighbor=cats[(index+1)%cats.length];const viewed=allProducts.filter(p=>p.id!==product.id&&(p.categoryId===neighbor||p.categoryId===product.categoryId&&p.subcategorySlug!==product.subcategorySlug)).slice(0,8);$("alsoViewed").replaceChildren(...viewed.map(recommendationCard))}
  function saveRecent(){let recent=[];try{const parsed=JSON.parse(localStorage.getItem("tabanji_recently_viewed"));recent=Array.isArray(parsed)?parsed:[]}catch{}const previous=recent.filter(x=>x!==product.id);recent=[product.id,...previous].slice(0,10);try{localStorage.setItem("tabanji_recently_viewed",JSON.stringify(recent))}catch{}const cards=previous.map(pid=>allProducts.find(p=>p.id===pid)).filter(Boolean).slice(0,8);if(cards.length>=2){$("recentSection").hidden=false;$("recentProducts").replaceChildren(...cards.map(recommendationCard))}}
  function recommendationAction(event){const button=event.target.closest("[data-action]");if(!button||!store)return;event.preventDefault();event.stopPropagation();const card=button.closest("[data-product-id]"),item=allProducts.find(p=>p.id===card?.dataset.productId);if(!item)return;if(button.dataset.action==="cart"){store.addToCart(item.id,1);showToast("Added to cart")}if(button.dataset.action==="favorite")showToast(store.toggleFavorite(item.id)?"Added to favorites":"Removed from favorites");if(button.dataset.action==="compare"){const r=store.toggleCompare(item.id);showToast(r.limit?"You can compare up to 4 products":r.added?"Added to compare":"Removed from compare")}refreshRecommend(card,item);store.updateHeaderCounters()}

  function openModal(modal,trigger){lastFocus=trigger||document.activeElement;activeModal=modal;modal.hidden=false;document.body.classList.add("modal-open");setTimeout(()=>modal.querySelector("button,input,select,textarea")?.focus(),0)}
  function closeModal(modal){modal.hidden=true;activeModal=null;document.body.classList.remove("modal-open");lastFocus?.focus()}
  function trapFocus(event){if(!activeModal||event.key!=="Tab")return;const focusable=[...activeModal.querySelectorAll("button:not(:disabled),a[href],input,select,textarea")].filter(x=>!x.hidden),first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}
  function openForm(type,trigger){$("formModalTitle").textContent=type==="review"?"Write a review":"Ask a question";$("ratingField").hidden=type!=="review";els.demoForm.dataset.type=type;openModal(els.formModal,trigger)}

  function searchSuggestions(){const q=els.search.value.trim().toLowerCase();if(!q){closeSuggestions();return}suggestionItems=allProducts.filter(p=>[p.title,p.brand,p.shortDescription,p.sku].join(" ").toLowerCase().includes(q)).slice(0,7);els.suggestions.replaceChildren(...(suggestionItems.length?suggestionItems.map((p,i)=>{const a=link("","product.html?id="+encodeURIComponent(p.id),"suggestion");a.id="product-suggestion-"+i;a.dataset.index=String(i);const t=el("span");t.append(el("strong","",p.title),el("small","",p.brand+" · "+p.sku));a.append(t,el("strong","",money(p.price,p.currency)));return a}):[el("p","suggestion","No results found")]));els.suggestions.hidden=false;els.search.setAttribute("aria-expanded","true")}
  function closeSuggestions(){els.suggestions.hidden=true;els.suggestions.replaceChildren();els.search.setAttribute("aria-expanded","false");suggestionIndex=-1;suggestionItems=[]}
  function selectSuggestion(next){const nodes=[...els.suggestions.querySelectorAll("[data-index]")];if(!nodes.length)return;suggestionIndex=(next+nodes.length)%nodes.length;nodes.forEach((n,i)=>n.classList.toggle("selected",i===suggestionIndex));els.search.setAttribute("aria-activedescendant",nodes[suggestionIndex].id)}
  function applyTheme(dark){document.body.classList.toggle("dark-mode",dark);els.theme.setAttribute("aria-pressed",String(dark));els.theme.textContent=dark?"☀":"☾";els.drawerTheme.textContent=dark?"☀️ Light theme":"🌙 Dark theme"}
  function toggleTheme(){const dark=!document.body.classList.contains("dark-mode");applyTheme(dark);try{localStorage.setItem("theme",dark?"dark":"light")}catch{}}
  function openDrawer(){els.menuOverlay.hidden=false;requestAnimationFrame(()=>els.menuOverlay.classList.add("visible"));els.drawer.classList.add("open");els.drawer.setAttribute("aria-hidden","false");els.openMenu.setAttribute("aria-expanded","true");document.body.classList.add("modal-open");els.closeMenu.focus()}
  function closeDrawer(){els.drawer.classList.remove("open");els.drawer.setAttribute("aria-hidden","true");els.menuOverlay.classList.remove("visible");els.openMenu.setAttribute("aria-expanded","false");document.body.classList.remove("modal-open");setTimeout(()=>els.menuOverlay.hidden=true,220);els.openMenu.focus()}

  let saved=null;try{saved=localStorage.getItem("theme")}catch{}applyTheme(saved?saved==="dark":matchMedia("(prefers-color-scheme:dark)").matches);els.theme.addEventListener("click",toggleTheme);els.drawerTheme.addEventListener("click",toggleTheme);els.openMenu.addEventListener("click",openDrawer);els.closeMenu.addEventListener("click",closeDrawer);els.menuOverlay.addEventListener("click",closeDrawer);
  els.search.addEventListener("input",searchSuggestions);els.search.addEventListener("keydown",e=>{if(e.key==="ArrowDown"){e.preventDefault();selectSuggestion(suggestionIndex+1)}if(e.key==="ArrowUp"){e.preventDefault();selectSuggestion(suggestionIndex-1)}if(e.key==="Escape")closeSuggestions()});els.searchForm.addEventListener("submit",e=>{e.preventDefault();if(suggestionIndex>=0&&suggestionItems[suggestionIndex])location.href="product.html?id="+encodeURIComponent(suggestionItems[suggestionIndex].id);else if(els.search.value.trim())location.href="products.html?search="+encodeURIComponent(els.search.value.trim())});
  if(!product){els.empty.hidden=false;els.content.hidden=true;if(!allProducts.length)els.empty.querySelector("p").textContent="Product data is unavailable. Please check data/products.js.";return}
  els.content.hidden=false;renderMain();renderGallery();store?.updateHeaderCounters();
  els.mainImage.addEventListener("error",()=>els.mainImage.src=fallback(),{once:true});els.lightboxImage.addEventListener("error",()=>els.lightboxImage.src=fallback(),{once:true});
  els.thumbs.addEventListener("click",e=>{const b=e.target.closest("[data-index]");if(b)showImage(Number(b.dataset.index))});els.prev.addEventListener("click",()=>showImage(galleryIndex-1));els.next.addEventListener("click",()=>showImage(galleryIndex+1));$("openLightbox").addEventListener("click",e=>openModal(els.lightbox,e.currentTarget));$("lightboxPrev").addEventListener("click",()=>showImage(galleryIndex-1));$("lightboxNext").addEventListener("click",()=>showImage(galleryIndex+1));els.lightbox.addEventListener("click",e=>{if(e.target===els.lightbox)closeModal(els.lightbox)});
  els.minus.addEventListener("click",()=>{els.qty.value=String(clampQty()-1);clampQty()});els.plus.addEventListener("click",()=>{els.qty.value=String(clampQty()+1);clampQty()});els.qty.addEventListener("change",clampQty);els.cart.addEventListener("click",()=>{if(store){store.addToCart(product.id,clampQty());showToast("Added "+clampQty()+" to cart")}else showToast("Cart is temporarily unavailable")});els.buy.addEventListener("click",()=>{if(store){store.addToCart(product.id,clampQty());location.href="cart.html"}});
  els.favorite.addEventListener("click",()=>{if(!store)return;showToast(store.toggleFavorite(product.id)?"Added to favorites":"Removed from favorites");refreshButtons()});els.compare.addEventListener("click",()=>{if(!store)return;const r=store.toggleCompare(product.id);showToast(r.limit?"You can compare up to 4 products":r.added?"Added to compare":"Removed from compare");refreshButtons()});
  $("shareButton").addEventListener("click",async()=>{try{if(navigator.share)await navigator.share({title:product.title,text:product.shortDescription,url:location.href});else{await navigator.clipboard.writeText(location.href);showToast("Product link copied")}}catch(error){if(error.name!=="AbortError")showToast("Unable to share this product")}});
  const tabs=[...document.querySelectorAll('[role="tab"]')];function selectTab(tab){tabs.forEach(t=>{const active=t===tab;t.setAttribute("aria-selected",String(active));$(t.getAttribute("aria-controls")).hidden=!active});tab.focus()}tabs.forEach((tab,i)=>{tab.addEventListener("click",()=>selectTab(tab));tab.addEventListener("keydown",e=>{let next=i;if(e.key==="ArrowRight")next=(i+1)%tabs.length;if(e.key==="ArrowLeft")next=(i-1+tabs.length)%tabs.length;if(e.key==="Home")next=0;if(e.key==="End")next=tabs.length-1;if(next!==i){e.preventDefault();selectTab(tabs[next])}})});els.reviewsLink.addEventListener("click",()=>{$("tab-reviews").click();$("panel-reviews").scrollIntoView({behavior:"smooth"})});
  document.querySelector(".details").addEventListener("click",e=>{const b=e.target.closest("[data-open-form]");if(b)openForm(b.dataset.openForm,b)});els.demoForm.addEventListener("submit",e=>{e.preventDefault();if(!els.demoForm.reportValidity())return;closeModal(els.formModal);els.demoForm.reset();showToast("This is a demo. Your message was not sent.")});document.querySelectorAll("[data-close]").forEach(b=>b.addEventListener("click",()=>closeModal($(b.dataset.close))));els.formModal.addEventListener("click",e=>{if(e.target===els.formModal)closeModal(els.formModal)});
  document.querySelectorAll(".recommend-grid").forEach(grid=>grid.addEventListener("click",recommendationAction));document.addEventListener("pointerdown",e=>{if(!e.target.closest(".search"))closeSuggestions()});document.addEventListener("keydown",e=>{trapFocus(e);if(e.key==="ArrowLeft"&&activeModal===els.lightbox)showImage(galleryIndex-1);if(e.key==="ArrowRight"&&activeModal===els.lightbox)showImage(galleryIndex+1);if(e.key!=="Escape")return;if(activeModal)closeModal(activeModal);else if(els.drawer.classList.contains("open"))closeDrawer();else closeSuggestions()});
});
