document.addEventListener("DOMContentLoaded",()=>{"use strict";
const $=id=>document.getElementById(id),data=typeof products!=="undefined"&&Array.isArray(products)?products:[],store=window.TabanjiStore,statuses=["new","paid","processing","shipped","ready","delivered"],labels={new:"Order placed",paid:"Payment confirmed",processing:"Processing",shipped:"Shipped",ready:"Ready",delivered:"Delivered",cancelled:"Cancelled"},payments={card:"Payment by card selected",cash:"Payment on delivery",bank:"Awaiting bank transfer"};let order=null,lastFocus=null,suggestions=[],suggestionIndex=-1,toastTimer;
const get=(key)=>{try{return localStorage.getItem(key)}catch{return null}},set=(key,value)=>{try{localStorage.setItem(key,value);return true}catch{return false}},parse=value=>{try{const result=JSON.parse(value);return result&&typeof result==="object"?result:null}catch{return null}},el=(tag,className,text)=>{const n=document.createElement(tag);if(className)n.className=className;if(text!==undefined)n.textContent=text;return n},money=(value,currency="USD")=>{try{return new Intl.NumberFormat("en-US",{style:"currency",currency,maximumFractionDigits:2}).format(Number(value)||0)}catch{return`${Number(value||0).toFixed(2)} ${currency}`}};
function toast(message){const box=$("status");if(!box)return;box.textContent=message;box.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>box.classList.remove("show"),2600)}
function lastOrder(){const candidate=parse(get("tabanji_last_order"));return candidate&&typeof candidate.orderNumber==="string"?candidate:null}
function maskEmail(value){const parts=String(value||"").split("@");if(parts.length!==2)return"Not provided";return`${parts[0].slice(0,1)}${"•".repeat(Math.min(5,Math.max(2,parts[0].length-1)))}@${parts[1]}`}
function maskPhone(value){const digits=String(value||"").replace(/\D/g,"");return digits?`••• ••• ${digits.slice(-4)}`:"Not provided"}
function addDetail(list,name,value){const row=el("div"),dt=el("dt","",name),dd=el("dd","",String(value??"—"));row.append(dt,dd);list.append(row)}
function deliveryName(){return order.delivery?.name||({courier:"Courier delivery",pickup:"Pickup point",store:"Store pickup"}[order.delivery?.method])||"Delivery"}
function destination(){const d=order.delivery||{};if(d.method==="courier")return[d.address1,d.address2,d.city,d.region,d.postalCode,d.country].filter(Boolean).join(", ")||"Address not provided";if(d.method==="pickup")return[d.location,d.city].filter(Boolean).join(", ")||"Pickup point not provided";return d.location||"Store location not provided"}
function timeline(){const list=$("timeline");list.replaceChildren();const isCancelled=order.status==="cancelled",current=Math.max(0,statuses.indexOf(order.status)),lastStep=order.delivery?.method==="courier"?"Out for delivery":"Ready for pickup",steps=["Order placed",order.paymentMethod==="cash"?"Payment pending":"Payment confirmed","Processing","Shipped",lastStep,"Delivered"];steps.forEach((name,index)=>{const item=el("li"),dot=el("span","dot",index<current?"✓":String(index+1)),title=el("span","",name),state=el("small","",isCancelled?(index===0?"Completed":"Stopped"):index<current?"Completed":index===current?"Current":"Pending");if(!isCancelled&&index<current)item.className="complete";if(!isCancelled&&index===current){item.className="current";item.setAttribute("aria-current","step")}if(isCancelled&&index===0)item.className="complete";item.append(dot,title,state);list.append(item)})}
function itemRow(item){const product=data.find(p=>p.id===item.productId),article=el("article","item"),image=el("img"),info=el("div","item-info"),title=el(product?"a":"strong","",product?.title||item.title||"Unavailable product"),quantity=el("span","",`Quantity: ${Number(item.quantity)||1}`),unit=el("div","item-price",money(item.price, item.currency||order.currency)),sum=el("strong","item-price",money((Number(item.price)||0)*(Number(item.quantity)||1),item.currency||order.currency));if(product){title.href=`product.html?id=${encodeURIComponent(product.id)}`;image.src=product.image;image.alt=product.title}else{image.alt="Product image unavailable"}image.addEventListener("error",()=>image.removeAttribute("src"),{once:true});info.append(title,quantity);article.append(image,info,unit,sum);return article}
function render(){if(!order)return;$("lookup").hidden=true;$("orderView").hidden=false;$("displayNumber").textContent=order.orderNumber;$("statusTitle").textContent=order.status==="cancelled"?"This order was cancelled":labels[order.status]||"Order status";$("statusBadge").textContent=labels[order.status]||String(order.status||"Unknown");const created=new Date(order.createdAt||Date.now()),validCreated=Number.isNaN(created.getTime())?new Date():created;$("createdAt").textContent=`Created ${new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short"}).format(validCreated)}`;$("heroTotal").textContent=money(order.total,order.currency);$("cancelledState").hidden=order.status!=="cancelled";timeline();
const details=$("orderDetails");details.replaceChildren();addDetail(details,"Payment",payments[order.paymentMethod]||order.paymentMethod||"—");addDetail(details,"Delivery",deliveryName());addDetail(details,"Estimate",order.delivery?.estimate||"To be confirmed");addDetail(details,"Currency",order.currency||"USD");const contact=$("contactDetails");contact.replaceChildren();addDetail(contact,"Customer",[order.customer?.firstName,order.customer?.lastName].filter(Boolean).join(" ")||"Not provided");addDetail(contact,"Email",maskEmail(order.customer?.email));addDetail(contact,"Phone",maskPhone(order.customer?.phone));$("destination").textContent=destination();$("estimate").textContent=`Estimated delivery: ${order.delivery?.estimate||"To be confirmed"}`;
const items=Array.isArray(order.items)?order.items:[];$("orderItems").replaceChildren(...items.map(itemRow));$("itemCount").textContent=`${items.reduce((n,item)=>n+(Number(item.quantity)||1),0)} items`;$("subtotal").textContent=money(order.subtotal,order.currency);$("discount").textContent=`−${money(order.discount,order.currency)}`;const promoDiscount=Number(order.promo?.discount)||0;$("promo").textContent=order.promo?.code?`${order.promo.code} · −${money(promoDiscount,order.currency)}`:`−${money(promoDiscount,order.currency)}`;$("deliveryPrice").textContent=Number(order.deliveryPrice)?money(order.deliveryPrice,order.currency):"Free";$("total").textContent=money(order.total,order.currency);$("demoStatus").value=statuses.includes(order.status)||order.status==="cancelled"?order.status:"new";$("cancelOrder").hidden=!["new","paid"].includes(order.status);document.title=`${order.orderNumber} | TABANJI`;}
function showLookup(message=""){order=null;$("orderView").hidden=true;$("lookup").hidden=false;$("viewLast").hidden=!lastOrder();$("orderError").textContent=message;$("orderNumber").setAttribute("aria-invalid",message?"true":"false");if(message)$("orderNumber").focus()}
function find(number){const saved=lastOrder();if(saved&&saved.orderNumber.toUpperCase()===String(number).trim().toUpperCase()){order=saved;render();return true}showLookup("Order not found. Check the number or view your last local order.");return false}
function saveStatus(status){if(!order)return;order.status=status;if(set("tabanji_last_order",JSON.stringify(order))){render();toast(`Status changed to ${labels[status]}.`)}else toast("Unable to save the demo status.")}
$("trackForm").addEventListener("submit",event=>{event.preventDefault();const number=$("orderNumber").value.trim();if(!number){showLookup("Enter an order number.");return}find(number)});$("viewLast").addEventListener("click",()=>{const saved=lastOrder();if(saved){order=saved;render()}});$("applyStatus").addEventListener("click",()=>saveStatus($("demoStatus").value));$("resetStatus").addEventListener("click",()=>saveStatus("new"));$("printOrder").addEventListener("click",()=>window.print());
$("copyNumber").addEventListener("click",async()=>{const value=order?.orderNumber||"";if(!value)return;try{await navigator.clipboard.writeText(value)}catch{const input=document.createElement("textarea");input.value=value;input.setAttribute("readonly","");input.style.position="fixed";input.style.opacity="0";document.body.append(input);input.select();try{document.execCommand("copy")}catch{}input.remove()}toast("Order number copied.")});
const modal=$("cancelModal");function openModal(){lastFocus=document.activeElement;modal.hidden=false;document.body.classList.add("lock");$("keepOrder").focus()}function closeModal(){modal.hidden=true;document.body.classList.remove("lock");lastFocus?.focus()}$("cancelOrder").addEventListener("click",openModal);$("keepOrder").addEventListener("click",closeModal);$("confirmCancel").addEventListener("click",()=>{closeModal();saveStatus("cancelled")});modal.addEventListener("click",event=>{if(event.target===modal)closeModal()});modal.addEventListener("keydown",event=>{if(event.key!=="Tab")return;const focusable=[$("keepOrder"),$("confirmCancel")],index=focusable.indexOf(document.activeElement);if(event.shiftKey&&index===0){event.preventDefault();focusable[1].focus()}else if(!event.shiftKey&&index===1){event.preventDefault();focusable[0].focus()}});
const drawer=$("drawer"),overlay=$("menuOverlay");function openMenu(){drawer.classList.add("open");drawer.setAttribute("aria-hidden","false");overlay.hidden=false;$("openMenu").setAttribute("aria-expanded","true");document.body.classList.add("lock");$("closeMenu").focus()}function closeMenu(){drawer.classList.remove("open");drawer.setAttribute("aria-hidden","true");overlay.hidden=true;$("openMenu").setAttribute("aria-expanded","false");document.body.classList.remove("lock");$("openMenu").focus()}$("openMenu").addEventListener("click",openMenu);$("closeMenu").addEventListener("click",closeMenu);overlay.addEventListener("click",closeMenu);
function theme(value){document.body.classList.toggle("dark",value==="dark");$("theme").textContent=value==="dark"?"☀":"☾";$("drawerTheme").textContent=value==="dark"?"☀ Light theme":"☾ Dark theme"}function toggleTheme(){const value=document.body.classList.contains("dark")?"light":"dark";try{localStorage.setItem("theme",value)}catch{}theme(value)}theme(get("theme")==="dark"?"dark":"light");$("theme").addEventListener("click",toggleTheme);$("drawerTheme").addEventListener("click",toggleTheme);
const search=$("search"),box=$("suggestions");function closeSuggestions(focus=false){box.hidden=true;box.replaceChildren();suggestions=[];suggestionIndex=-1;search.setAttribute("aria-expanded","false");search.removeAttribute("aria-activedescendant");if(focus)search.focus()}function renderSuggestions(){const q=search.value.trim().toLowerCase();if(!q){closeSuggestions();return}suggestions=data.filter(p=>[p.title,p.brand,p.sku].join(" ").toLowerCase().includes(q)).slice(0,6);box.replaceChildren();suggestions.forEach((p,index)=>{const a=el("a","",p.title);a.href=`product.html?id=${encodeURIComponent(p.id)}`;a.id=`track-suggestion-${index}`;a.setAttribute("role","option");box.append(a)});if(!suggestions.length)box.append(el("p","","No products found"));box.hidden=false;search.setAttribute("aria-expanded","true")}function move(delta){const links=[...box.querySelectorAll("a")];if(!links.length)return;suggestionIndex=(suggestionIndex+delta+links.length)%links.length;links.forEach((a,i)=>a.classList.toggle("selected",i===suggestionIndex));search.setAttribute("aria-activedescendant",links[suggestionIndex].id)}search.addEventListener("input",renderSuggestions);search.addEventListener("keydown",event=>{if(event.key==="ArrowDown"){event.preventDefault();move(1)}else if(event.key==="ArrowUp"){event.preventDefault();move(-1)}else if(event.key==="Enter"&&suggestionIndex>=0){event.preventDefault();location.href=box.querySelectorAll("a")[suggestionIndex].href}else if(event.key==="Escape")closeSuggestions(true)});$("searchForm").addEventListener("submit",event=>{event.preventDefault();if(search.value.trim())location.href=`products.html?search=${encodeURIComponent(search.value.trim())}`});document.addEventListener("pointerdown",event=>{if(!event.target.closest(".search"))closeSuggestions()});document.addEventListener("keydown",event=>{if(event.key==="Escape"){if(!modal.hidden)closeModal();else if(drawer.classList.contains("open"))closeMenu();else closeSuggestions(true)}});
const saved=lastOrder(),requested=new URLSearchParams(location.search).get("order");if(requested){$("orderNumber").value=requested;find(requested)}else if(saved){order=saved;render()}else showLookup();if(store?.updateHeaderCounters)store.updateHeaderCounters();
});
